logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

database:
  name: yachiyo
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  host: "localhost"
  port: 5432

  table:
    api_depository: "api_depository"
    conversation: "conversation"
    long_term: "long_term"
    knowledge_base: "vector_store"

llm:
  api_key: ${API_KEY}
